apiVersion: v1
kind: Node
metadata:
  annotations:
    kwok.x-k8s.io/node: fake
  name: kwok-node
  labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: kwok-node
      kubernetes.io/os: linux
      kubernetes.io/role: agent
      kwok.x-k8s.io/kwokctl-scale: node
      node-role.kubernetes.io/agent: ""
      kubevirt.io/schedulable: "true"
      type: kwok
spec:
  taints:
  - effect: NoSchedule
    key: kwok.x-k8s.io/node
    value: fake
status:
  capacity:
    cpu: "32"
    memory: "256Gi"
    ephemeral-storage: "100Gi"
    pods: "110"
    devices.kubevirt.io/kvm: "1k"
    devices.kubevirt.io/tun: "1k"
    devices.kubevirt.io/vhost-net: "1k"
  allocatable:
    cpu: "32"
    memory: "256Gi"
    ephemeral-storage: "100Gi"
    pods: "110"
    devices.kubevirt.io/kvm: "1k"
    devices.kubevirt.io/tun: "1k"
    devices.kubevirt.io/vhost-net: "1k"
  nodeInfo:
    architecture: amd64
    kubeProxyVersion: fake
    kubeletVersion: fake
    operatingSystem: linux
