apiVersion: v1
kind: Node
metadata:
  annotations:
    kwok.x-k8s.io/node: fake
  name: node-3
  labels:
      beta.kubernetes.io/arch: arm64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: arm64
      kubernetes.io/hostname: kwok-node-0
      kubernetes.io/os: linux
      kubernetes.io/role: agent
      kwok.x-k8s.io/kwokctl-scale: node
      node-role.kubernetes.io/agent: ""
      type: kwok
      topology.kubernetes.io/region: us-west-2
spec:
status:
    allocatable:
      cpu: 4
      memory: 4Gi
      pods: "55"
    capacity:
      cpu: "4"
      memory: 4Gi
      pods: "55"
    nodeInfo:
      architecture: arm64
      kubeProxyVersion: fake
      kubeletVersion: fake
      operatingSystem: linux
---
apiVersion: v1
kind: Node
metadata:
  annotations:
    kwok.x-k8s.io/node: fake
  name: node-4
  labels:
      beta.kubernetes.io/arch: arm64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: arm64
      kubernetes.io/hostname: kwok-node-0
      kubernetes.io/os: linux
      kubernetes.io/role: agent
      kwok.x-k8s.io/kwokctl-scale: node
      node-role.kubernetes.io/agent: ""
      type: kwok
      topology.kubernetes.io/region: us-west-2
spec:
status:
    allocatable:
      cpu: 4
      memory: 4Gi
      pods: "55"
    capacity:
      cpu: "4"
      memory: 4Gi
      pods: "55"
    nodeInfo:
      architecture: arm64
      kubeProxyVersion: fake
      kubeletVersion: fake
      operatingSystem: linux
