apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: default
spec:
  containers:
  - name: fake-container
    image: fake-image
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "2.7G"
        cpu: "2.7"
      limits:
        memory: "3G"
        cpu: "3"
  tolerations:
  - key: "kwok.x-k8s.io/node"
    operator: "Exists"
    effect: "NoSchedule"
  