apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: default
spec:
  containers:
  - name: fake-container
    image: fake-image
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "1.2G"
        cpu: "1.2"
      limits:
          memory: "1.5G"
          cpu: "1.5"
  tolerations:
  - key: "kwok.x-k8s.io/node"
    operator: "Exists"
    effect: "NoSchedule"
