apiVersion: kwok.x-k8s.io/v1alpha1
kind: ClusterExec
metadata:
  name: example-cluster-exec
spec:
  selector:
    matchNamespaces:
    - default
  execs:
  - containers:
    - nginx
    local:
      workDir: "/home"
      envs:
      - name: ENV_VAR
        value: "value"
