---
# Source: cluster-autoscaler/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kwok-provider-config
  namespace: default
data: 
  config: |-
    apiVersion: v1alpha1
    readNodesFrom: cluster
    nodegroups:
      fromNodeLabelKey: kubernetes.io/hostname
    nodes:
    configmap:
      name: kwok-provider-templates
    kwok: {}
---
# Source: cluster-autoscaler/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kwok-provider-templates
  namespace: default
data: 
  templates: |-
    # if you see '\n' everywhere, remove all the trailing spaces
    apiVersion: v1
    items:
    - apiVersion: v1
      kind: Node
      metadata:
        annotations:
          kwok.x-k8s.io/node: fake
          metrics.k8s.io/resource-metrics-path: /metrics/nodes/node-000000/metrics/resource
          node.alpha.kubernetes.io/ttl: "0"
        creationTimestamp: "2024-07-15T05:41:02Z"
        labels:
          beta.kubernetes.io/arch: amd64
          beta.kubernetes.io/os: linux
          kubernetes.io/arch: amd64
          kubernetes.io/hostname: node-000000
          kubernetes.io/os: linux
          kubernetes.io/role: agent
          kwok.x-k8s.io/kwokctl-scale: node
          node-role.kubernetes.io/agent: ""
          type: kwok
        name: node-000000
        resourceVersion: "228"
        uid: 81178ba3-0658-4213-87ed-b20750b084f1
      spec:
        podCIDR: 10.0.0.1/24
        podCIDRs:
        - 10.0.0.1/24
      status:
        addresses:
        - address: kwok-kwok-kwok-controller
          type: Hostname
        allocatable:
          cpu: "32"
          memory: 256Gi
          pods: "110"
        capacity:
          cpu: "32"
          memory: 256Gi
          pods: "110"
        conditions:
        - lastHeartbeatTime: "2024-07-15T05:41:02Z"
          lastTransitionTime: "2024-07-15T05:41:02Z"
          message: kubelet is posting ready status
          reason: KubeletReady
          status: "True"
          type: Ready
        - lastHeartbeatTime: "2024-07-15T05:41:02Z"
          lastTransitionTime: "2024-07-15T05:41:02Z"
          message: kubelet has sufficient memory available
          reason: KubeletHasSufficientMemory
          status: "False"
          type: MemoryPressure
        - lastHeartbeatTime: "2024-07-15T05:41:02Z"
          lastTransitionTime: "2024-07-15T05:41:02Z"
          message: kubelet has no disk pressure
          reason: KubeletHasNoDiskPressure
          status: "False"
          type: DiskPressure
        - lastHeartbeatTime: "2024-07-15T05:41:02Z"
          lastTransitionTime: "2024-07-15T05:41:02Z"
          message: kubelet has sufficient PID available
          reason: KubeletHasSufficientPID
          status: "False"
          type: PIDPressure
        - lastHeartbeatTime: "2024-07-15T05:41:02Z"
          lastTransitionTime: "2024-07-15T05:41:02Z"
          message: RouteController created a route
          reason: RouteCreated
          status: "False"
          type: NetworkUnavailable
        daemonEndpoints:
          kubeletEndpoint:
            Port: 10247
        nodeInfo:
          architecture: amd64
          bootID: ""
          containerRuntimeVersion: kwok-v0.6.0
          kernelVersion: kwok-v0.6.0
          kubeProxyVersion: kwok-v0.6.0
          kubeletVersion: kwok-v0.6.0
          machineID: ""
          operatingSystem: linux
          osImage: ""
          systemUUID: ""
        phase: Running
    kind: List
    metadata:
      resourceVersion: ""