apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: default
  labels:
    region: us-west-2
spec:
  containers:
  - name: fake-container
    image: fake-image
    ports:
    - containerPort: 80
  tolerations:
  - key: "kwok.x-k8s.io/node"
    operator: "Exists"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # It says that the pod must be scheduled onto a node that satisfies the specified conditions, and if there's no such node, the pod won't be scheduled.
        nodeSelectorTerms:
        - matchExpressions: # matches a label assigned to a node
          - key: region
            operator: In # If the value of the key 'name' is 'node1', then the condition is satisfied.
            values:
            - us-west-2