apiVersion: v1
kind: Pod
metadata:
  name: high-priority-pod
spec:
  priorityClassName: high-priority
  containers:
  - name: high-priority-container
    image: fake
    resources:
      requests:
        cpu: "3"
      limits:
        cpu: "3"