apiVersion: v1
kind: Node
metadata:
  annotations:
    kwok.x-k8s.io/node: fake
  name: node-01
  labels:
      beta.kubernetes.io/arch: arm64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: arm64
      kubernetes.io/hostname: kwok-node-0
      kubernetes.io/os: linux
      minikube.k8s.io/name: kwok-node-0
      minikube.k8s.io/primary: "true"
      node-role.kubernetes.io/control-plane: ""
      node-role.kubernetes.io/master: ""
      type: kwok
spec:
  taints:
  - effect: NoSchedule
    key: kwok.x-k8s.io/node
    value: fake
status:
    allocatable:
      cpu: "2"
      memory: 512Gi
      pods: "110"
    capacity:
      cpu: "2"
      memory: 512Gi
      pods: "110"
    nodeInfo:
      architecture: arm64
      kubeProxyVersion: fake
      kubeletVersion: fake
      operatingSystem: linux

