apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-nginx
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       nginx
  updatePolicy:
    updateMode: "Auto"
#   resourcePolicy:
#     containerPolicies:
#       - containerName: '*'
#         minAllowed:
#           cpu: 300m
#         maxAllowed:
#           cpu: 500m  # The maximum cpu vpa will be allocating even if demand is higher.
#         controlledResources: ["cpu"]
